# Generated by Django 4.1.2 on 2022-10-23 04:17

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_name", models.CharField(max_length=254, unique=True)),
                (
                    "description",
                    models.TextField(
                        max_length=1000, null=True, verbose_name="Descripción"
                    ),
                ),
                ("title", models.CharField(max_length=254)),
                (
                    "language",
                    models.CharField(
                        choices=[("PY", "Python"), ("JS", "JavaScript")],
                        max_length=3,
                        verbose_name="Lenguaje de programación",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                ("position", models.PositiveSmallIntegerField(verbose_name="Posición")),
                (
                    "instructions",
                    models.FilePathField(
                        match=".*\\.md",
                        max_length=254,
                        path=api.models.Level.level_path,
                    ),
                ),
                (
                    "tests",
                    models.FilePathField(
                        match=".*\\.js",
                        max_length=254,
                        path=api.models.Level.level_path,
                    ),
                ),
                ("title", models.CharField(max_length=254, verbose_name="Titulo")),
                (
                    "estimated_duration",
                    models.PositiveSmallIntegerField(
                        verbose_name="Duracion estimada (en horas)"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="api.course",
                        verbose_name="Curso asociado",
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "position")},
            },
        ),
        migrations.CreateModel(
            name="CompletedLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solution", models.TextField(max_length=2500)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.level"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
