# Generated by Django 4.1.2 on 2022-10-23 06:08

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_course_level_completedlevel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="completedlevel",
            options={
                "verbose_name": "nivel completado",
                "verbose_name_plural": "niveles completados",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "curso"},
        ),
        migrations.AlterModelOptions(
            name="level",
            options={"verbose_name": "nivel", "verbose_name_plural": "niveles"},
        ),
        migrations.AddField(
            model_name="course",
            name="course_price",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Gratuito"), (1, "De pago")],
                default=0,
                verbose_name="precio del curso",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="membership_status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Gratuita"), (1, "Pro")],
                default=0,
                verbose_name="Membresía",
            ),
        ),
        migrations.AlterField(
            model_name="completedlevel",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.level",
                verbose_name="nivel",
            ),
        ),
        migrations.AlterField(
            model_name="completedlevel",
            name="solution",
            field=models.TextField(max_length=2500, verbose_name="solución"),
        ),
        migrations.AlterField(
            model_name="completedlevel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=254, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="level",
            name="estimated_duration",
            field=models.PositiveSmallIntegerField(
                verbose_name="Duracion estimada (en minutos)"
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="instructions",
            field=models.FilePathField(
                match=".*\\.md",
                max_length=254,
                path=api.models.get_level_path,
                verbose_name="Instrucciones",
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="tests",
            field=models.FilePathField(
                match=".*\\.js",
                max_length=254,
                path=api.models.get_level_path,
                verbose_name="Pruebas del curso",
            ),
        ),
        migrations.CreateModel(
            name="CourseBought",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.course",
                        verbose_name="curso",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "curso comprado",
                "verbose_name_plural": "cursos comprados",
            },
        ),
    ]
