# Generated by Django 4.1.2 on 2022-10-23 09:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_level_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="instructions",
            field=models.FileField(
                max_length=254,
                upload_to=api.models.get_level_path,
                verbose_name="Instrucciones",
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="tests",
            field=models.FileField(
                max_length=254,
                upload_to=api.models.get_level_path,
                verbose_name="Pruebas del curso",
            ),
        ),
    ]
