# Generated by Django 4.1.3 on 2022-11-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_level_instructions_alter_level_tests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="instructions",
            field=models.TextField(verbose_name="Instrucciones"),
        ),
        migrations.AlterField(
            model_name="level",
            name="tests",
            field=models.TextField(verbose_name="Pruebas del curso"),
        ),
    ]
