# Generated by Django 4.1.3 on 2022-11-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_course_path_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="completedlevel",
            unique_together={("user", "level")},
        ),
    ]
